### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by gvsurenderreddy** [supunlakmal/thismypc#77]
Hello sir
There is no information about how to install it on my PC and access it from any where on the internet.Can you give us an insight of the same please
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by supunlakmal** [comment]
Hi, @gvsurenderreddy.
Did you clone and run all npm commands as say on?
 https://github.com/supunlakmal/thismypc/blob/master/README.md

**Comment by gvsurenderreddy** [comment]
Sir ,
Its not full desktop control like Teamviewer or anydesk it just Harddisk folder sharing right

**Comment by supunlakmal** [comment]
Hi, @gvsurenderreddy
Yes it currently show HD file and folders. We working on adding new items like in other softwares.
Thanks.
